repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.1
    hooks:
      - id: sqlfluff-fix
        additional_dependencies: ["sqlfluff-templater-dbt==3.4.1"]
        language: python
        args: [--config=pyproject.toml]
        files: ^models/.*\.sql$
      - id: sqlfluff-lint
        additional_dependencies: ["sqlfluff-templater-dbt==3.4.1"]
        args: [--config=pyproject.toml]
        files: ^models/.*\.sql$

  # can add more hooks here https://github.com/dbt-checkpoint/dbt-checkpoint/blob/main/HOOKS.md
  # - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  #   rev: v2.0.4
  #   hooks:
  #     - id: dbt-parse
  #     - id: dbt-docs-generate
  #       args: ["--cmd-flags", "++no-compile"]
  #     - id: check-column-desc-are-same
  #     - id: check-model-has-tests
  #       args: ["--test-cnt", "1", "--"]
  # - repo: local
  #   hooks:
  # - id: sqlfluff-fix
  #   language: system
  #   name: sqlfluff fix
  #   entry: uv run sqlfluff fix --config pyproject.toml models/
  #   pass_filenames: false

  # - id: sqlfluff-lint
  #   language: system
  #   name: sqlfluff fix
  #   entry: uv run sqlfluff lint --config pyproject.toml models/
  #   pass_filenames: false

  # - id: sqlfluff-lint
  #   language: system
  #   name: sqlfluff lint
  #   entry: uv run sqlfluff lint --config pyproject.toml enhanced_de_prompt_engineering/queries
  #   pass_filenames: false
