services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ${PWD}/docker/postgres_bootstrap.sql:/docker-entrypoint-initdb.d/postgres_bootstrap.sql
    networks:
      - api_network

  dbt_runner:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: dbt_kimball_local
    depends_on:
      - postgres
    networks:
      - api_network
    links:
      - postgres:postgres
    command: dbt build
    volumes:
      - ${PWD}/models/:/home/appuser/models

networks:
  api_network:
