jyablonski_kimball_example:
  outputs:

    dev:
      type: postgres
      threads: 8
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: dbt_stg

    prod:
      type: postgres
      threads: 8
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: dbt_prod

    snowflake:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_HOST') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: DBT_ROLE_PROD
      database: production
      warehouse: DBT_ROLE_PROD_WAREHOUSE
      schema: TEST_SCHEMA
      threads: 8
      query_tag: "dbt"  # Optional

  target: dev

dbt_ci:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: dbt_stg
      
  target: dev


elementary:
  outputs:
    default:
      type: "postgres"
      host: "localhost"
      port: 5432
      user: "postgres"
      password: postgres
      dbname: "postgres"
      schema: "dbt_stg"
      threads: 1