name: dbt CD

on: 
  pull_request:
    types: [closed]
    branches:
      - master

env:
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
  AWS_REGION : "us-east-1"
  DBT_USER_STG: hi
  DBT_PASS_STG: hiv2
  DBT_USER_PROD: aa
  DBT_PASS_PROD: aav2


permissions:
      id-token: write
      contents: read

jobs:
  deploy_pipeline:
    name: Deploy Pipeline
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: kimball-dbt-cd
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Env Vars
        id: set_env_vars
        run: |
          if [[ "${{github.base_ref}}" == "master" || "${{github.ref}}" == "refs/heads/master" ]]; then
            echo "DBT_ENV=dev" >> "$GITHUB_ENV"
            echo "DBT_USER=$DBT_USER_STG" >> "$GITHUB_ENV"
            echo "DBT_PASS=$DBT_PASS_STG" >> "$GITHUB_ENV"
            fi

          if [[ "${{github.base_ref}}" == "production" || "${{github.ref}}" == "refs/heads/production" ]]; then
            echo "DBT_ENV=dev" >> "$GITHUB_ENV"
            echo "DBT_USER=$DBT_USER_PROD" >> "$GITHUB_ENV"
            echo "DBT_PASS=$DBT_PASS_PROD" >> "$GITHUB_ENV"
            fi

      - name: Install Requirements
        run: |
          pip install poetry
          poetry install

      - name: Install dbt Dependencies
        run: |
          poetry run dbt deps --target dev --profiles-dir profiles/

      - name: Get Manifest File
        env:
          DBT_ENV: ${{ env.DBT_ENV}}
        run: |
          echo $DBT_ENV $DBT_USER $DBT_PASS $DBT_USER_PROD
          aws s3 cp s3://${{ env.S3_BUCKET }}/${{ env.DBT_ENV }}/manifest.json manifest.json

      - name: Build changed dbt Models
        env:
          DBT_ENV: ${{ env.DBT_ENV}}
        run: |
          make up
          poetry run dbt build --target ${{ env.DBT_ENV }} --profiles-dir profiles/ --profile dbt_ci --select +state:modified+ --state ./
          make down

      - name: Upload Manifest to S3
        env:
          DBT_ENV: ${{ env.DBT_ENV}}
        run: |
          aws s3 cp target/manifest.json s3://${{ env.S3_BUCKET }}/${{ env.DBT_ENV }}/manifest.json